### ISSUE TITLE
Drag & Drop does not work for players

### ISSUE THREAD

**Issue by r-valyar** [saif-ellafi/foundryvtt-drag-all-to-hotbar#1]
Players are unable to drag & drop anything in their marco bar even if Enable Macro settings is not. It seems this mod functions only for GM. Is this the intention?

**Comment by saif-ellafi** [comment]
Hello, thank you @r-valyar, no this is not intended, just a very fresh new module.
Going to check it out and attempt to solve it!

**Comment by saif-ellafi** [comment]
Very interesting, I did not know that Foundry does not let players drag and drop at all!

**Comment by saif-ellafi** [comment]
Wait, it does work for items and journals, the players need to be able to see them of course.

**Comment by r-valyar** [comment]
Yes, foundry is not good at all when it comes to player's. FG is lightyears ahead. 
But your mod is absolutely necessary for Foundry. I hope you can sort out the drag&drop for players somehow.

**Comment by r-valyar** [comment]
But I can't drag & drop the charsheet, even if I am owner?

**Comment by saif-ellafi** [comment]
I think you are right, only for Characters doesn't work, no?

**Comment by saif-ellafi** [comment]
Apparently, Drag & Drop of Actors will work if you give this permission to players. Will add this on documentation for now, maybe there is a workaround.
![image](https://user-images.githubusercontent.com/27952699/145673914-8a0ba7bf-993e-480f-8d2d-25bcef744feb.png)

**Comment by saif-ellafi** [comment]
@r-valyar I found a solution to make this work without having to give such permissions :)

**Comment by r-valyar** [comment]
You are the man :)

**Comment by saif-ellafi** [comment]
Released and fixed! Have fun! let me know for any further feedback.
