### ISSUE TITLE
Re-Implement Compendium handling

### ISSUE THREAD

**Issue by esheyw** [saif-ellafi/foundryvtt-drag-all-to-hotbar#13]
Not really sure why this was removed; as noted in my last comment on #9 , Foundry did not implement this. I stole the code from the last version that shipped with it for some personal macros, but I see no reason why it shouldn't be part of the module still.

**Comment by esheyw** [comment]
Also you might want to update the readme to reflect what the module actually does at this point, since it claims a lot more than is still in it.

**Comment by saif-ellafi** [comment]
Hi @esheyw - done, added Compendium folders support, actor icons too.
Still Foundry v11 has some issues with items but I reported that to them.
have fun

**Comment by saif-ellafi** [comment]
Hi @esheyw - Foundry has fixed their issues now in V11.306 - So the rest of the features should work well too.
