### ISSUE TITLE
Bug: Conflict with Compendium Folders?

### ISSUE THREAD

**Issue by esheyw** [saif-ellafi/foundryvtt-drag-all-to-hotbar#4]
While [Compendium Folders](https://github.com/earlSt1/vtt-compendium-folders) is active, dragging a compendium to the hotbar does nothing, as far as I can tell? Tried it with everything else disabled and it still breaks. No errors thrown.

**Comment by saif-ellafi** [comment]
Hi @esheyw ! Fixed! Enjoy
