### ISSUE TITLE
v10 could still use this module

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-drag-all-to-hotbar#9]
With your Depreciation notice, it looks like you consider this module no longer needed as of Foundry v10, but I'd argue this module is still super useful. In v10, dragging a song or a playlist into the hotbar only opens up the configuration menu, doesn't actually play the song. This is the primary reason why I use your module in v9, and it's still just as relevant in v10 IMO!

**Comment by saif-ellafi** [comment]
Hey GambetTV - Glad to see you around, you've been quite an active users of my modules for a while :)

Ok, I'll reconsider it, need to make an analysis of which features can still break through. I was concerned that Foundry is also going in the same direction and don't want to spend many hours to have it dropped then.

Plus the one on Core foundry doesn't seem to work well with Items (it only works with items from characters), but it is very hard for me to disable Foundry new logic to put mine in front.

Best!

**Comment by GambetTV** [comment]
Yeah, honestly if most things work with the new version of Foundry, then maybe just a module for music specifically? I wish I were more knowledgeable about these things, but coding is not my strong suit. Definitely don't put yourself out there though if you don't think it's worth your time anymore. I just know that in one of my campaigns literally 3 rows of my hotbar is filled with music because of your module. It's made changing music on the fly so easy that it's really enhanced the production value of my campaigns by always having a song ready for every mood. So it's super useful to anyone like me, that's for sure!

**Comment by uniwars** [comment]
Hi, I +1 about music in hotbar being really useful. I use this module just for that too. Just having to drop playlist/sfx in hotbar before playing and then having all the sounds ready to use is rawesome.

**Comment by gsterling** [comment]
As far as I can see, it still works in V10 for existing macros.

If anyone else wants to downgrade to keep using it download the old 1.0.2 Version https://github.com/saif-ellafi/foundryvtt-drag-all-to-hotbar/releases/tag/1.0.2 and place it manually in the modules directory of foundry. You can then lock the version in the module page in foundry's setup.

And +1

You macro is way better than the official implementation.

**Comment by saif-ellafi** [comment]
Alright, @GambetTV @uniwars @gsterling - you all make a fair point, I was wary to see if Foundry v10 slowly added the missing features. But if there are benefitial features still, I will test the macros that are still useful in V10 and revive the module :)

**Comment by saif-ellafi** [comment]
Guys @GambetTV @uniwars @gsterling - how do you even make it work still in v10?
I see Foundry already places a Macro when drag and dropping to the hotbar, which takes precedence over what my module works. This means, even for playlist and  soundtracks, Foundry V10 is doing stuff before this module.

**Comment by saif-ellafi** [comment]
Ah I see you mean "for existing macros", so not for new drag and dropped

**Comment by GambetTV** [comment]
To be clear, I'm still using v9 until my favorite modules get updated for v10. I simply tested out v10 to see what's up with it, which is where I discovered the uselessness of v10's music drag and drop functions.

**Comment by esheyw** [comment]
I don't know anything about the sound macros, but I'd love if this gets updated just so I can continue dragging compendia to the macro bar, which is *not* part of v10.

**Comment by saif-ellafi** [comment]
Hi @esheyw @GambetTV @gsterling @uniwars 
1.1.0 Released and done! Let me know if it work swell
The version in V10 supports Roll Tables (to immediately roll from them), and Playlists and Sounds
Thanks

**Comment by esheyw** [comment]
Hey, haven't had a chance to test this til now, could you please reinstate compedia-opening macros?
